### ISSUE TITLE
HIP out of memory during generation of texture

### ISSUE THREAD

**Issue by MaximPerry** [deepbeepmeep/Hunyuan3D-2GP#30]
First of all - thank you for this amazing work. I do see the improvement on my VRAM by a lot, with barely any impact on 3D models. This is absolutely awesome.

Unfortunately, I quickly hit a wall. The "Gen Shape" works just fine, but "Gen Textured Shape" causes an error after a couple of minutes: 
```
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 22.50 GiB. GPU 0 has a total capacity of 15.98 GiB of which 13.69 GiB is free. Of the allocated memory 917.46 MiB is allocated by PyTorch, and 1012.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.
```
I have a 16GB VRAM card (AMD RX 7600 XT) with 32 GB RAM. The main reason I wanted to try [Hunyuan3D-2GP](https://github.com/deepbeepmeep/Hunyuan3D-2GP) over the original is because with the original, generating textures would make my GPU run out of memory, so I figured I would tried this one but I get the same fundamental issue.

I'm also noticing at the bottom of the Web UI:
```
Activated Model - Shape Generation (tencent/Hunyuan3D-2mini/hunyuan3d-dit-v2-mini-turbo) ; Texture Generation (Hunyuan3D-2)
```
Does that mean "mini-turbo" is not loaded for the texture generation?

Thank you in advance.

**Comment by Elefant-Freeciv** [comment]
Use TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1. This worked for me on a 7900 xtx torch 2.5.1-rocm6.2.

**Comment by Elefant-Freeciv** [comment]
You will also probably need to read [https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1/issues/195#issuecomment-3832378510](https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1/issues/195#issuecomment-3832378510)

**Comment by MaximPerry** [comment]
Hey @Elefant-Freeciv Thank you for trying to help me! I have tried running Hunyuan3D-2GP with:
```shell
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
```
and modifying `hy3gen/texgen/differentiable_renderer/mesh_render.py` at line 128 with:
```python
self.device = "cpu"
```
as you suggested, but unfortunately I'm still running out of memory when generating a textured shape on my 16GB VRAM card... Although, instead of running out of memory by 22.50 GiB as before, it's only by 3.75 GiB now:

```
Error
HIP out of memory. Tried to allocate 3.75 GiB. GPU 0 has a total capacity of 15.98 GiB of which 2.79 GiB is free. Of the allocated memory 7.71 GiB is allocated by PyTorch, and 626.65 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
So I guess this is progress.

It appears only one other user was able to make Hunyuan3D-2's textured shape generation work on a 16GB AMD GPU, by: "_dissecting the batch image to 2-3 per generate._" (from: https://github.com/Tencent-Hunyuan/Hunyuan3D-2/issues/52#issuecomment-3181029183), which sounds like it's the way to go. However, I wasn't able to reproduce this result myself. The user did not publish their code fix.

**Comment by Elefant-Freeciv** [comment]
What is the command you use to run? Also, what is your python environment?

**Comment by MaximPerry** [comment]
I'm using the following launch commands:
```shell
#!/bin/bash
export FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"
export GPU_ARCHS="gfx1102"
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
python3 gradio_app.py --profile 1 --turbo --mc_algo mc --enable_flashvdm --enable_t23d --port 7063
```
And I'm running Hunyuan3D-2GP inside of a docker container using the [rocm6.4.3_ubuntu22.04_py3.10_pytorch_release_2.6.0](https://hub.docker.com/layers/rocm/pytorch/rocm6.4.3_ubuntu22.04_py3.10_pytorch_release_2.6.0/) image.

**Comment by Elefant-Freeciv** [comment]
Try --profile 4, --profile 1 is the max vram max ram profile. From the readme.md: 

> You can choose between 5 profiles depending on your hardware:
> 
> HighRAM_HighVRAM (1)
> HighRAM_LowVRAM (2)
> LowRAM_HighVRAM (3)
>  LowRAM_LowVRAM (4)
>  VerylowRAM_LowVRAM (5)
> 
> Each profile's name describes the targeted level of RAM and VRAM consumptions.
> Usualy the lower the profile number the faster the generation.

**Comment by Elefant-Freeciv** [comment]
You could also try a conda env with `conda env create -f h3d-rocm.yml`
h3d-rocm.yml:
```name: H3D-ROCM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_5
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - amd-gsplat==1.5.3+30c1e78
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - basicsr==1.4.2
      - blinker==1.9.0
      - bpy==4.0.0
      - brotli==1.2.0
      - cffi==2.0.0
      - cfgv==3.5.0
      - chardet==5.2.0
      - click==8.3.1
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - colorspacious==1.1.2
      - comm==0.2.3
      - configargparse==1.7
      - contourpy==1.3.2
      - custom-rasterizer==0.1
      - cycler==0.12.1
      - cython==3.2.4
      - dash==3.4.0
      - dataclasses-json==0.6.7
      - decorator==4.4.2
      - deepspeed==0.18.4
      - deprecated==1.3.1
      - diffusers==0.30.0
      - diso==0.2.0
      - distlib==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.0
      - embreex==2.17.7.post7
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - facexlib==0.3.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.20.0
      - filterpy==1.4.5
      - flash-attn==2.8.3
      - flask==3.1.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - future==1.0.0
      - gfpgan==1.3.8
      - gradio==4.44.1
      - gradio-client==1.3.0
      - gradio-litmodel3d==0.0.1
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - identify==2.6.16
      - imageio==2.36.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - ipydatawidgets==4.3.5
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jaxtyping==0.3.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning==2.6.1
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - lmdb==1.7.5
      - lpips==0.1.4
      - lxml==6.0.2
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - minio==7.2.20
      - mmgp==3.2.7
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.1
      - nodeenv==1.10.0
      - numba==0.63.1
      - numpy==1.24.4
      - omegaconf==2.3.0
      - onnxruntime==1.16.3
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - optimum-quanto==0.2.6
      - orjson==3.11.5
      - packaging==26.0
      - pandas==2.2.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.4.0
      - pillow-heif==0.22.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pluggy==1.6.0
      - plyfile==1.1.3
      - pooch==1.8.2
      - pre-commit==4.5.1
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==4.25.8
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==23.0.0
      - pybind11==2.13.4
      - pycollada==0.9.3
      - pycolmap==3.10.0
      - pycparser==3.0
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygltflib==1.16.3
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymatting==1.1.14
      - pymeshlab==2022.2.post3
      - pyparsing==3.3.2
      - pyquaternion==0.9.9
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.22
      - pythreejs==2.4.2
      - pytorch-lightning==1.9.5
      - pytorch-triton-rocm==3.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - realesrgan==0.3.0
      - referencing==0.37.0
      - regex==2026.1.15
      - rembg==2.0.65
      - rerun-sdk==0.23.1
      - retrying==1.4.2
      - rich==13.3.5
      - roma==1.5.4
      - rootutils==1.0.7
      - rpds-py==0.30.0
      - rtree==1.4.1
      - ruff==0.14.14
      - safehttpx==0.1.7
      - safetensors==0.4.4
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.14.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shapely==2.1.2
      - shellingham==1.5.4
      - spaces==0.47.0
      - stack-data==0.6.3
      - starlette==0.46.2
      - svg-path==7.0
      - sympy==1.13.1
      - tb-nightly==2.18.0a20240726
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.24
      - tokenizers==0.21.4
      - tomli==2.4.0
      - tomlkit==0.12.0
      - torch==2.5.1+rocm6.2
      - torchaudio==2.5.1+rocm6.2
      - torchdiffeq==0.2.5
      - torchmetrics==1.6.0
      - torchvision==0.20.1+rocm6.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - traittypes==0.2.3
      - transformers==4.49.0
      - trimesh==4.4.7
      - typeguard==4.4.4
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - tyro==1.0.5
      - tzdata==2025.3
      - uniception==0.1.6
      - uvicorn==0.34.3
      - vhacdx==0.0.10
      - virtualenv==20.36.1
      - viser==0.2.11
      - wadler-lindig==0.1.7
      - wcwidth==0.3.5
      - websockets==12.0
      - widgetsnbextension==4.0.15
      - xatlas==0.0.9
      - xxhash==3.6.0
      - yapf==0.43.0
      - yarl==1.22.0
      - yourdfpy==0.0.60
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/usr/.conda/envs/H3D-ROCM
```

**Comment by MaximPerry** [comment]
I should have specified earlier that I have already tried all profiles from 1 to 5, none of them did the trick for me. Shape generation works, but Shape + Textures runs out of memory no matter the profile. 

I could however try the conda environment you suggested... I'll let you know if I do. For now, I'm really trying to focus on making it work in the docker container it's already running in. But if I give up, I'll try that next. Thanks!

**Comment by Elefant-Freeciv** [comment]
The conda env and docker container are not mutually exclusive. You can use conda to manage your python env in docker. Or use the your favored python package manager, but use the exact python packages listed. It should be the same either way. I went with conda because it's easy to export a complete list of environment packages.

**Comment by Elefant-Freeciv** [comment]
A note: I have dual 7900 xtx gpus, so 24 gb vram. But I don't notice usage going over ~10gb, with nvtop for monitoring.
